"""
Integration test for Task 5: Tool Factory Integration verification.
Verifies that generated tools get Pydantic models and schema validation works.
"""
import os
import tempfile
from pathlib import Path

import pytest

from backend.services.tool_factory import ToolFactory
from backend.services.tool_creation_service import ToolCreationService
from backend.models.schemas.tool_creation import ToolCreationRequest, ToolParameter
from backend.models.database import get_db_context
from backend.core.tool_registry import tool_registry


class TestToolFactorySchemaValidation:
    """Verify tool factory integration with Pydantic schema validation."""

    def setup_method(self):
        """Ensure clean registry for each test."""
        # Remove any test tools from registry
        for key in list(tool_registry.tools.keys()):
            if key.startswith("test_factory_"):
                tool_registry.deregister_tool(key)

    def teardown_method(self):
        """Clean up after test."""
        for key in list(tool_registry.tools.keys()):
            if key.startswith("test_factory_"):
                tool_registry.deregister_tool(key)

    def test_generated_tool_gets_pydantic_model(self):
        """Test that a tool generated by tool_factory gets a Pydantic model."""
        with get_db_context() as db:
            factory = ToolFactory()

            # Create a simple tool file directly
            tool_name = "test_factory_basic"
            parameters = [
                ToolParameter(name="query", type="string", description="Search query", required=True),
                ToolParameter(name="max_results", type="integer", description="Max results", required=False, default=5),
            ]

            request = ToolCreationRequest(
                tool_name=tool_name,
                description="Test tool for factory validation",
                parameters=parameters,
                code_template="result = {'status': 'success', 'query': query, 'max_results': max_results}",
                test_cases=[],
                authorized_tiers=["0xxxx", "1xxxx"],
                created_by_agentium_id="00001",
                rationale="Integration test",
            )

            # Generate the tool file
            tool_path = factory.generate_tool_file(request)
            assert tool_path.exists()

            # Create the service and activate
            svc = ToolCreationService(db)
            # Need to create a staging entry first - let's use the factory method directly
            # by calling load_tool to simulate what activate_tool does

            load_result = factory.load_tool(tool_name)
            assert load_result["loaded"]

            # Register in registry (this is what activate_tool does)
            tool_registry.register_tool(
                name=tool_name,
                description=request.description,
                function=load_result["tool_instance"].execute,
                parameters={
                    p.name: {"type": p.type, "description": p.description}
                    for p in request.parameters
                },
                authorized_tiers=request.authorized_tiers,
            )

            # Verify the tool has a pydantic_model
            tool = tool_registry.get_tool(tool_name)
            assert tool is not None
            assert "pydantic_model" in tool
            assert tool["pydantic_model"] is not None

            # Verify schema validation works - valid input
            import asyncio
            result = asyncio.run(tool_registry.execute_tool_async(
                tool_name, query="test", max_results="10"  # string "10" should coerce to int
            ))
            assert result["status"] == "success"
            assert result["max_results"] == 10  # Coerced to int

            # Verify schema validation rejects invalid - missing required
            result = asyncio.run(tool_registry.execute_tool_async(
                tool_name, max_results=5  # missing required 'query'
            ))
            assert result["status"] == "error"
            assert result["error"]["type"] == "schema_validation_error"
            assert result["error"]["details"][0]["type"] == "missing"
            assert result["error"]["details"][0]["loc"] == ("query",)

    def test_generated_tool_enum_validation(self):
        """Test that enum parameters get proper Literal validation."""
        with get_db_context() as db:
            factory = ToolFactory()

            tool_name = "test_factory_enum"
            parameters = [
                ToolParameter(
                    name="provider",
                    type="string",
                    description="Search provider",
                    required=True,
                    # Enum will be in the schema
                ),
            ]

            request = ToolCreationRequest(
                tool_name=tool_name,
                description="Test tool with enum",
                parameters=parameters,
                code_template="result = {'status': 'success', 'provider': provider}",
                test_cases=[],
                authorized_tiers=["0xxxx", "1xxxx"],
                created_by_agentium_id="00001",
                rationale="Integration test",
            )

            tool_path = factory.generate_tool_file(request)
            assert tool_path.exists()

            load_result = factory.load_tool(tool_name)
            assert load_result["loaded"]

            tool_registry.register_tool(
                name=tool_name,
                description=request.description,
                function=load_result["tool_instance"].execute,
                parameters={
                    "provider": {
                        "type": "string",
                        "description": "Search provider",
                        "enum": ["auto", "tavily", "brave"]
                    },
                },
                authorized_tiers=request.authorized_tiers,
            )

            tool = tool_registry.get_tool(tool_name)
            assert "pydantic_model" in tool

            import asyncio
            # Valid enum value
            result = asyncio.run(tool_registry.execute_tool_async(
                tool_name, provider="tavily"
            ))
            assert result["status"] == "success"
            assert result["provider"] == "tavily"

            # Invalid enum value
            result = asyncio.run(tool_registry.execute_tool_async(
                tool_name, provider="google"
            ))
            assert result["status"] == "error"
            assert result["error"]["type"] == "schema_validation_error"
            assert result["error"]["details"][0]["type"] == "literal_error"

    def test_generated_tool_optional_with_default(self):
        """Test that optional parameters with defaults work correctly."""
        with get_db_context() as db:
            factory = ToolFactory()

            tool_name = "test_factory_optional_default"

            request = ToolCreationRequest(
                tool_name=tool_name,
                description="Test tool with optional default",
                parameters=[],
                code_template="""
query = kwargs.get('query', 'default_query')
max_results = kwargs.get('max_results', 42)
return {'status': 'success', 'query': query, 'max_results': max_results}
""",
                test_cases=[],
                authorized_tiers=["0xxxx", "1xxxx"],
                created_by_agentium_id="00001",
                rationale="Integration test",
            )

            tool_path = factory.generate_tool_file(request)
            assert tool_path.exists()

            load_result = factory.load_tool(tool_name)
            assert load_result["loaded"]

            tool_registry.register_tool(
                name=tool_name,
                description=request.description,
                function=load_result["tool_instance"].execute,
                parameters={
                    "query": {"type": "string", "description": "Query", "optional": True, "default": "default_query"},
                    "max_results": {"type": "integer", "description": "Max results", "optional": True, "default": 42},
                },
                authorized_tiers=request.authorized_tiers,
            )

            tool = tool_registry.get_tool(tool_name)
            assert "pydantic_model" in tool

            import asyncio
            # No params - should use defaults
            result = asyncio.run(tool_registry.execute_tool_async(tool_name))
            assert result["status"] == "success"
            assert result["query"] == "default_query"
            assert result["max_results"] == 42


if __name__ == "__main__":
    pytest.main([__file__, "-v"])