"""Add model pricing table

Revision ID: 001
Revises: 000_combined_migration
Create Date: 2026-06-21 08:45:15.987633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_add_model_pricing_table'
down_revision = '000_combined_migration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricings',
    sa.Column('model_id', sa.String(length=150), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('input_rate_per_1m', sa.Float(), nullable=False),
    sa.Column('output_rate_per_1m', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agentium_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_pricings_agentium_id'), 'model_pricings', ['agentium_id'], unique=True)
    op.create_index(op.f('ix_model_pricings_model_id'), 'model_pricings', ['model_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_pricings_model_id'), table_name='model_pricings')
    op.drop_index(op.f('ix_model_pricings_agentium_id'), table_name='model_pricings')
    op.drop_table('model_pricings')
    # ### end Alembic commands ###