"""Add context_window column to model_pricings table

Revision ID: 022_add_context_window_to_model_pricings
Revises: 021_add_workflow_versions_table
Create Date: 2026-09-01 10:19:57.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022_add_context_window_to_model_pricings'
down_revision = '021_add_workflow_versions_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_pricings', sa.Column('context_window', sa.Integer(), nullable=True, default=128000))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_pricings', 'context_window')
    # ### end Alembic commands ###