"""Add context_window column to model_pricings table

Revision ID: a1b2c3d4e5f6
Revises: 001_fix_alembic_version_length
Create Date: 2026-09-01 10:19:57.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '001_fix_alembic_version_length'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_pricings', sa.Column('context_window', sa.Integer(), nullable=True, default=128000))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_pricings', 'context_window')
    # ### end Alembic commands ###