"""add meta_data column to ethos

Revision ID: 7a73fcef3cfe
Revises: 798130950386
Create Date: 2026-08-01 20:50:07.882230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a73fcef3cfe'
down_revision = '798130950386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ethos', sa.Column('meta_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ethos', 'meta_data')
    # ### end Alembic commands ###