#!/usr/bin/env bash
# scripts/pin-digests.sh — Fetch latest digests for all base images.
# Run this locally to update .pinned-digests.env and Dockerfile FROM lines.
set -euo pipefail

OUTFILE=".pinned-digests.env"

echo "🐍 Fetching python:3.11-slim-bookworm digest..."
PYTHON_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' python:3.11-slim-bookworm 2>/dev/null | cut -d'@' -f2)
if [ -z "$PYTHON_DIGEST" ]; then
    echo "Downloading python:3.11-slim-bookworm..."
    docker pull -q python:3.11-slim-bookworm
    PYTHON_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' python:3.11-slim-bookworm 2>/dev/null | cut -d'@' -f2)
fi

echo "⬢ Fetching node:20-alpine digest..."
NODE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' node:20-alpine 2>/dev/null | cut -d'@' -f2)
if [ -z "$NODE_DIGEST" ]; then
    echo "Downloading node:20-alpine..."
    docker pull -q node:20-alpine
    NODE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' node:20-alpine 2>/dev/null | cut -d'@' -f2)
fi

echo "🌐 Fetching nginx:alpine digest..."
NGINX_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' nginx:alpine 2>/dev/null | cut -d'@' -f2)
if [ -z "$NGINX_DIGEST" ]; then
    echo "Downloading nginx:alpine..."
    docker pull -q nginx:alpine
    NGINX_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' nginx:alpine 2>/dev/null | cut -d'@' -f2)
fi

echo ""
echo "=== Digests captured ==="
echo "PYTHON_DIGEST=$PYTHON_DIGEST"
echo "NODE_DIGEST=$NODE_DIGEST"
echo "NGINX_DIGEST=$NGINX_DIGEST"

# Write to .env file
cat > "$OUTFILE" <<__EOF__
# Auto-generated by scripts/pin-digests.sh
# Run 'bash scripts/pin-digests.sh' to refresh
PYTHON_DIGEST=$PYTHON_DIGEST
NODE_DIGEST=$NODE_DIGEST
NGINX_DIGEST=$NGINX_DIGEST
generated_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
__EOF__

echo "✅ Digests written to $OUTFILE"
