@echo off
:: ============================================================================
:: Agentium Voice Bridge Bootstrap
:: Auto-generated by docker-compose voice-autoinstall service.
:: ============================================================================
set AGENTIUM_DIR=%USERPROFILE%\.agentium
set LOG=%AGENTIUM_DIR%\bootstrap.log

:: Ensure log directory exists
if not exist "%AGENTIUM_DIR%" mkdir "%AGENTIUM_DIR%"

echo [%DATE% %TIME%] Bootstrap started > "%LOG%"

:: REPO_ROOT is baked in by voice-autoinstall.sh
set "REPO=AGENTIUM_REPO_ROOT"
set "SETUP=%REPO%\scripts\setup.ps1"

echo Baked REPO: %REPO% >> "%LOG%"

:: If the baked path doesn't exist, try to find the repo dynamically
if not exist "%SETUP%" (
    echo [%DATE% %TIME%] Baked path not found, searching... >> "%LOG%"
    
    :: Search for scripts\setup.ps1 on each drive (checks current working dir too)
    for %%D in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
        if exist "%%D:\Agentium\scripts\setup.ps1" (
            set "REPO=%%D:\Agentium"
            set "SETUP=%%D:\Agentium\scripts\setup.ps1"
            echo [%DATE% %TIME%] Found repo at: %%D:\Agentium >> "%LOG%"
            goto :found_repo
        )
    )

    :: Try current directory's parent (if scripts is a subdirectory of CWD)
    if exist "scripts\setup.ps1" (
        set "REPO=%CD%"
        set "SETUP=%CD%\scripts\setup.ps1"
        echo [%DATE% %TIME%] Found repo at current directory >> "%LOG%"
        goto :found_repo
    )
    
    :: If we're in a subdirectory, try going up
    if exist "..\scripts\setup.ps1" (
        pushd ..
        set "REPO=%CD%"
        set "SETUP=%CD%\scripts\setup.ps1"
        echo [%DATE% %TIME%] Found repo at parent directory >> "%LOG%"
        popd
        goto :found_repo
    )

    :: Search up to 3 levels deep on E: drive (common location)
    set "FOUND="
    for /f "tokens=*" %%F in ('dir /s /b "E:\scripts\setup.ps1" 2^>nul') do (
        if not defined FOUND (
            set "FOUND=1"
            pushd "%%~dpF.."
            set "REPO=%CD%"
            set "SETUP=%%F"
            echo [%DATE% %TIME%] Found repo at: %%F >> "%LOG%"
            popd
            goto :found_repo
        )
    )
    
    :found_repo
)

echo Final SETUP path: %SETUP% >> "%LOG%"

if not exist "%SETUP%" (
    echo [%DATE% %TIME%] ERROR: setup.ps1 not found >> "%LOG%"
    echo.
    echo =====================================================================
    echo  Voice bridge bootstrap could not find setup.ps1.
    echo  Run it directly from your Agentium repo folder:
    echo.
    echo    powershell -ExecutionPolicy Bypass -File "scripts\setup.ps1"
    echo.
    echo  (The script no longer requires administrator access.)
    echo =====================================================================
    echo.
    type "%LOG%"
    pause
    exit /b 1
)

echo [%DATE% %TIME%] Launching setup.ps1... >> "%LOG%"

:: Launch the installer â€” no admin needed for VBS mode (default)
powershell -NoProfile -ExecutionPolicy Bypass -File "%SETUP%"

echo [%DATE% %TIME%] Installer finished >> "%LOG%"
echo Done. Check "%LOG%" for details.
pause
exit /b 0